version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: vinkit-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - vinkit-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vinkit-backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-super-secret-key-change-in-production
    depends_on:
      - redis
    volumes:
      - ./backend:/app
    networks:
      - vinkit-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vinkit-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - vinkit-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: vinkit-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - vinkit-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  vinkit-network:
    driver: bridge
